### ISSUE TITLE
unknown revision nanomsg.org/go/mangos/v2.0.1

### ISSUE THREAD

**Issue by gabrielruiu** [nanomsg/mangos#81]
While trying to build a go project, which uses mangos-v2, I get the following error:
```
go: finding nanomsg.org/go/mangos/v2 v2.0.1
go: nanomsg.org/go/mangos/v2@v2.0.1: unknown revision nanomsg.org/go/mangos/v2.0.1
go: error loading module requirements
```

This is the `require` statement in my `go.mod`:
```
...
require nanomsg.org/go/mangos/v2 v2.0.1
...
```

I am using `go-1.11`.

Not sure what I did wrong.

**Comment by gdamore** [comment]
I haven't had enough cycles to properly diagnose this.  Modules (or the transition to them) have been a significant headache. I guess it's a good thing they are still opt-in.

**Comment by edermi** [comment]
Right now I'm running into the same problem - unfortunately mangos v2 is also broken with dep (see #79) so mangos-v2 does currently not work with both major dependency managers for golang.

**Comment by kleijnweb** [comment]
Does anyone have a workable workaround (aside from switching back to Dep) while @gdamore finds the time to address this?

**Comment by gdamore** [comment]
With the new go modules support, I wonder if we should just create a branch of the old git repo (mangos v1) and move mangos v2 there.

I wish there was a clear document describing how git, branches, and go modules, along with vanity names, were all meant to work.

**Comment by kleijnweb** [comment]
That will probably work (with the needed tags also applied): it does seem like de modules vendoring gets confused when `/v2` is a package suffix instead of a semver (tag) notation. 

The verbose output of `go get` gives a little bit of insight in what it tries to do:

```
$ go get -v nanomsg.org/go/mangos/v2
Fetching https://nanomsg.org/go/mangos/v2?go-get=1
Parsing meta tags from https://nanomsg.org/go/mangos/v2?go-get=1 (status code 200)
get "nanomsg.org/go/mangos/v2": found meta tag get.metaImport{Prefix:"nanomsg.org/go/mangos/v2", VCS:"git", RepoRoot:"https://github.com/nanomsg/mangos-v2"} at https://nanomsg.org/go/mangos/v2?go-get=1
go: finding nanomsg.org/go/mangos/v2 latest
Fetching https://nanomsg.org/go/mangos?go-get=1
Parsing meta tags from https://nanomsg.org/go/mangos?go-get=1 (status code 404)
Fetching https://nanomsg.org/go?go-get=1
Parsing meta tags from https://nanomsg.org/go?go-get=1 (status code 404)
Fetching https://nanomsg.org?go-get=1
Parsing meta tags from https://nanomsg.org?go-get=1 (status code 200)
go get nanomsg.org/go/mangos/v2: no matching versions for query "latest"
```
`https://nanomsg.org/go/mangos` doesn't exists as v1 is at `nanomsg.org/go-mangos`. Then it just strips path segments until it runs out of them.

So making sure that `https://nanomsg.org/go/mangos` produces the correct metadata and adjusting go.mod to remove the v2 is a step in the right direction. It would make sense to me that `go get -v nanomsg.org/go/mangos/v2` then works, but I haven't tried that with any projects. It is possible (seems unlikely) that only `go get -v nanomsg.org/go/mangos` followed by manual adjustment of import paths and `tidy` will work, but then maybe you'll also need 1.x.x tags? 

Personally I would opt for creating a v2 branch in v1 and make both `nanomsg.org/go/mangos` and `nanomsg.org/go-mangos` point to that repo, move the tickets, label everything v1 and v2. Only problem is see with that is that v1 installed as `nanomsg.org/go/mangos` might not work as some of the internal import paths reference `nanomsg.org/go-mangos`. But you could probably address that by creating a new 1.x version that uses the new import path and a big disclaimer that if you try to install old 1.x versions, you should use the old vanity path.

No easy solutions here as far as I can see. Once you have enabled modules, you can also not import anything from GOPATH so I also don't see a temporary workaround for us users other than dumping either mangos-vr or go modules.

**Comment by gdamore** [comment]
Thanks for your insights.  I'll see if I can experiment with this.  Unfortunately it can be difficult to experiment with the current repos, because I don't want to break stuff for people who might be successfully using this stuff.

It's unlikely I'll be able to make progress on this before the weekend. :/

**Comment by gabrielruiu** [comment]
I agree with the approach to merge the 2 projects and separate them by branches. Don't know how much effort that is or what impact it might have though. 

I'm a fan of the module system so any adaption in that direction gets a vote from me.

**Comment by gabrielruiu** [comment]
Another option is to merge the v2 project into the v1 project (at github.com/nanomsg/mangos), either directly in master or in a separate branch if you need to maintain them separately, and then tag it with a `v3.0.0` version. 

This is an option recommended for projects migrating to the module system. To just jump a version even though there's no API changes. Described [here](https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher)

**Comment by gdamore** [comment]
So there is a bug in the upstream go project, where vanity import paths and v2+ modules just don't play well together.  A fix is in progress, and I'm told to expect a go 1.12.1 that fixes, along with 1.13.  There really isn't much more I can do in the meantime, unless it is to rename the project entirely, which is something I utterly loathe to do.

Probably once go 1.12.1 comes out, I'll start a mangos v3 branch with a different import path (probably will be go.nanomsg.org/mangos/v3 -- but details remain TBD.)

I will remind folks that go modules at this point are still considered "experimental", and folks adopting them are early adopters.  The fact that they still have some rough edges should be expected.

**Comment by tapir** [comment]
The error I get is a little bit different so I thought I might add it here as well.
This is a new project, as a module named `daemon`. trying to build reqrep example
```
$ go build
go: finding nanomsg.org/go/mangos/v2 latest
go: finding nanomsg.org/go/mangos/v2/protocol/req latest
go: finding nanomsg.org/go/mangos/v2/protocol/rep latest
go: finding nanomsg.org/go/mangos/v2/protocol latest
go: finding nanomsg.org/go/mangos v2.0.0+incompatible
go: downloading nanomsg.org/go/mangos v2.0.0+incompatible
go: extracting nanomsg.org/go/mangos v2.0.0+incompatible
build daemon: cannot load nanomsg.org/go/mangos/v2: cannot find module providing package nanomsg.org/go/mangos/v2
```

**Comment by gdamore** [comment]
This should work with go 1.12.1 now.  I have not had time to sufficiently test.

**Comment by gdamore** [comment]
This works with modern enough golang.  Closing.
